services:
  # Servicio web para la aplicación Vue.js  - type: web
    name: websapmenu
    env: node
    repo: https://github.com/alexjfj20/websapmenu
    buildCommand: npm install && npx vue-cli-service build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: SYNC_ENABLED
        value: true
      - key: SYNC_INTERVAL
        value: 60000
      - key: DATABASE_URL
        fromDatabase:
          name: websap-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: websap-menu
    env: node
    buildCommand: cp -f package-worker.json package.json && npm install
    startCommand: node server-worker.js
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: true

databases:
  # Base de datos PostgreSQL
  - name: websap-db
    plan: free
    databaseName: websap
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere